[package]
name = "flkv"
version = "0.1.0"
edition = "2018"


[lib]
name = "flkv"
crate-type = ["cdylib", "staticlib"]


[dependencies]
rusty-leveldb = "0.3.5"

[build-dependencies]
cbindgen = "0.19.0"

[profile.release]
opt-level = 'z'
panic = 'abort'
lto = true
codegen-units = 1